# -*- coding: utf-8 -*-
"""class(class x).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aqcTZmUxxI3AhEeVWM8JllBFbhULz8Vw
"""

class x:
  def A(self):
    pass
  def B(self):
    pass
  def AC(cls):
    pass