# -*- coding: utf-8 -*-
"""class(self).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aqcTZmUxxI3AhEeVWM8JllBFbhULz8Vw
"""

class B:
  def setvar(self,a,b):
    self.x=a
    c=a*b
    self.y=c