# -*- coding: utf-8 -*-
"""class(chage).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aqcTZmUxxI3AhEeVWM8JllBFbhULz8Vw
"""

class A():
  name="ali"
  age=25

A.name="Reza"
print(A.name)

test=A()
test.name="ahamad"
print(test.age)