# -*- coding: utf-8 -*-
"""class(3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g3Wcpv3PnpTeK5pAnC52e_h5zvD960cr
"""

class person:
    def __init__(self,s,n):
      self.score=s
      self.name=n
      print("hello")



h=person (56,"hasan")