# -*- coding: utf-8 -*-
"""function(n==k).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ozCQ0WaVHSXaMrMKCUW5rzSIzebWUpBN
"""

def majmoe(i):
  sum=0
  while i!=0:
    sum=0
    t//=10
  return sum

  def function1(n):
    for i in range(n):
      k=Majmoe(i)
      if k==n:
        return k
   return print("not find")