# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q_B3u1yMVmthVdsKZ1WiEOSUFfs46tKq
"""

def inputlist():
  L=[]
  k=0
  while k!=5:
    k=int(input('please Enter number'))
    L.append(k)
  return L