# -*- coding: utf-8 -*-
"""list(2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q_B3u1yMVmthVdsKZ1WiEOSUFfs46tKq
"""

def inputlist():
  L=[]
  k=0
  while 2>1:
    k=int(input())
    if k==5:
      break
    L.append(k)
  return L