# -*- coding: utf-8 -*-
"""max_min(count).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q_B3u1yMVmthVdsKZ1WiEOSUFfs46tKq
"""

def mxamin_count(L):
  L.sort()
  count_min = L.count(L[0])
  count_max = L.count(L[-1])
  return L[-1],count_max,L[0],count_min