# -*- coding: utf-8 -*-
"""max_min(sort).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q_B3u1yMVmthVdsKZ1WiEOSUFfs46tKq
"""

def max_min(tr):
  tr.sort()
  return tr[-1],tr[0]
  A=inputlist()
  M,m=max_min(A)
  print(M,m)