# -*- coding: utf-8 -*-
"""maximum100.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yv0kd9GloVOKgVWKjTp-FImiklE0OUOX
"""

def maximum100():
  a=input()
  a=int(a)
  max=a
  for i in range(99):
    a=int(input())
    if a>max:
      max=a
  return max