# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CaFoCjM-4JGvYGSc2RGVXp-wjSi59L6K
"""

def func1():
  print()
print('salam')
func1()
func1()
print('khodahafez')