# -*- coding: utf-8 -*-
"""وراثت.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X-qi0E_VORBpLoZwJpOTv5I5k3S5DvYb
"""

class Brand:
  brand_1='Amazon'
  brand_2='Eloay'
  brand_3='oln'
class Produt:
  prod_1='onlion Ecommere'
  prod_2='onlion store'
  prod_3='onlion buy'
class Popularity(Brand,Produt):
  prod_pop=100
  prod_pop=70
  prod_pop=50
obj=Popularity()
print(obj.brand_1+'isa'+obj.prod_2)