# -*- coding: utf-8 -*-
"""وراثت سلسله ترکیی کد کامل.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X-qi0E_VORBpLoZwJpOTv5I5k3S5DvYb
"""

class Money:
  money=200000000

class Doctor(Money):
  docor="this doctor is famous...."

class Medical(Money):
  medical="this hospial is equipped"

class Hospital(Doctor,Medical):
  hospital="this hospital has a  doctor"

obj=Hospital()