# -*- coding: utf-8 -*-
"""وراثت سلسله مراتبی کد کامل.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X-qi0E_VORBpLoZwJpOTv5I5k3S5DvYb
"""

class Store:
  def __init__(self,store):
    self.s=store

class Hyper(Store):
  def __init__(self,store,produt):
    super().__init__(store)
    self.p=produt

class HomeAppliances(Store):
    def __init__(self,store,appliances):
     super().__init__(store)
     self.a=appliances

class Meson(Store):
  def __init__(self,store,clothes):
    super().__init__(store)
    self.c=clothes

obj1=Store("bigstore")
obj3=HomeAppliances("bigstore","appliances")
obj4=Meson("bigstore","clothes")
print(obj4.c)